trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
    - job: SecondJob
      steps:
      - bash: echo Build Second Job
- stage: DevDeploy
  variables:
    nagarathna: Dev
  dependsOn: Build
  jobs:
    - job: DevFist
      steps:
      - bash: echo $(nagarathna)DeployJob
    - job: DevSeccond
      steps:
      - bash: echo Dev Second Job
- stage: QADeploy
  variables:
     nagarathna: 
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - bash: echo $(nagarathna)QADeploy
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo $(nagarathna)ProdDeploy